### ISSUE TITLE
Mark troop positions on minimap

### ISSUE THREAD

**Issue by LittleBigKiller** [ignis05/cinnamon-game#158]

**Comment by LittleBigKiller** [comment]
I need help with getting a token list to cross-reference with current players in the lobby (and their slots/colors)

**Comment by ignis05** [comment]
@LittleBigKiller everything you need can be received using `socket.getSession()`
![image](https://user-images.githubusercontent.com/48099798/59160001-7eb37980-8ad1-11e9-98dc-a5f475cfc7fe.png)

**Comment by LittleBigKiller** [comment]
@ignis05 <3

**Comment by LittleBigKiller** [comment]
#171
