### ISSUE TITLE
Block type weight

### ISSUE THREAD

**Issue by ignis05** [ignis05/cinnamon-game#166]
Currently moving through all block types costs the same amount of movement points.
Are we still planning to adjust that?
And if yes, then are weights implemented in pathfinding?
![2019-06-09 20_47_40- Cinnamon  Game](https://user-images.githubusercontent.com/48099798/59162850-61de6c80-8af8-11e9-837a-b9181e0499d8.png)

**Comment by LittleBigKiller** [comment]
IIRC we can't really implement weights, because the library still doesn't have weighted paths
